// Create selectors
const form = document.querySelector('.memeform');
const imgUrl = document.querySelector('#imgUrl');
const topText = document.querySelector('#topText');
const bottomText = document.querySelector('#bottomText');
const memes = document.querySelector('#memes');

// Variable to check that no error generated by input image url
let imgCheck = 1;

// Form Submission
form.addEventListener('submit', function(event) {
    event.preventDefault();

    // New elements to hold the generated meme
    const newMeme = document.createElement('div');
    const newImg = document.createElement('img');
    const newTopText = document.createElement('div');
    const newBottomText = document.createElement('div');
    const memeContainer = document.createElement('div');
    const removeBtn = document.createElement('button');
    
    // Giving classes to elements for styling and for event listener for remove button
    newMeme.className = 'meme'
    newTopText.classList.add('text', 'top');
    newBottomText.classList.add('text','bottom');
    memeContainer.className = 'memeContainer';
    removeBtn.className = 'remove';

    // Setting user input values to their corresponding elements and delete button text
    newImg.src = imgUrl.value;
    newTopText.innerText = topText.value.toUpperCase();
    newBottomText.innerText = bottomText.value.toUpperCase();
    removeBtn.innerText = 'Delete Meme';

    // Append image and text to meme then meme to the container
    newMeme.append(newImg, newTopText, newBottomText);
    memeContainer.append(newMeme, removeBtn);

    // Delete Button
    memeContainer.addEventListener('click', function (event) {

        if (event.target.className === 'remove') {
            event.target.parentNode.remove();
        }
    })

    // Check if img url provides an error. If so, alert user and set imgCheck to 0.
    newImg.onerror = function() {
        alert('Uh oh! Looks like an invalid image source!');
        imgCheck = 0;
    }

    // Timeout to ensure function runs after imgCheck updates
    setTimeout(function() {
    
        // Check that there is no error with user input image and that the field is not empty before attempting to append the meme 
        if (imgCheck && imgUrl.value !== '') {

            memes.append(memeContainer);

            imgUrl.value = '';
            topText.value = '';
            bottomText.value = '';

        }

        // Return imgCheck to 1 so that following submissions can pass
        imgCheck = 1;
    }, 100)
})